## example config input
## SAC Coniguration file with toml


[QmcReader]

    beta = 8.0                              # inverse temperature
    number_of_tgrids = 160                  # number of imgainary-time points
    number_of_bins = 1000                   # number of bins in QMC measurements
    number_of_bootstraps = 5e3              # number of bootstrap samples
    pace_of_rebin = 1                       # pace of rebin


[SAC]

    [SAC.Types]
        kernel_type = "fermion"             # type of the kernel, e.g. fermion, boson
        update_type = "single"              # type of MC updating modes, e.g. single, pair

    [SAC.FreqGrids]
        freq_interval = 1e-5                # interval of hyperfine grids
        spec_interval = 1e-2                # interval of spectral grids
        freq_min = -8.0                     # minimum of the frequency domain
        freq_max = +8.0                     # maximum of the frequency domain

    [SAC.Measure]
        number_of_bins = 5                  # number of bins for the measurments during the annealing process
        size_of_bin = 1e3                   # size ( number of samples ) of perticular one bin during the annealing process
        collecting_steps = 1e5              # number of samples for the collection of the recovered spectral functions

    [SAC.Annealing]
        theta = 1e8                         # initial sampling temperature
        number_of_deltas = 1e3              # number of delta functions
        annealing_rate = 0.9                # decay rate of the annealing
        max_annealing_steps = 5e3           # maximum of the annealing steps
        pace_of_stabilization = 10          # pace of the numerical stabilization ( recompute the chi2 )

